name: Solar System Planets Workflow
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

env:
    MONGO_URI: "mongodb+srv://${{ vars.MONGO_USERNAME }}:${{ secrets.MONGO_PASSWORD }}@solar-test-db.rusjxzi.mongodb.net/superdata?retryWrites=true&w=majority"
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up NodeJS Version 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            
            - name: environment info
              run: |
                  echo "MONGO_URI: $MONGO_URI"
                  echo "MONGO_USERNAME: $MONGO_USERNAME"

            - name: Install dependencies
              run: npm install

            - name: Run unit tests
              run: npm test

